version: "3.7"

services:
  react_front:
    container_name: react-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: >
      bash -c "
          yarn install
          yarn start"

networks:
  default:
      name: react_network
